name: Stockfish build

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build. If empty - build current.'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Stockfish repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'official-stockfish/Stockfish'
          ref: ${{ inputs.commit }}

      - name: Setup MSYS2 (CLANG64 environment)
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: >-
            git
            make
            mingw-w64-clang-x86_64-clang

      - name: Extract version info
        id: version
        shell: msys2 {0}
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(git log -1 --format=%cs)
          ARTIFACT_NAME="stockfish-avx512icl-git-${COMMIT}-${DATE}-win64"
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
          
      - name: Configure and build 
        shell: msys2 {0}
        run: |
          cd src
          make -j$(nproc) build COMP=clang ARCH=x86-64-avx512icl
          make strip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.version.outputs.artifact_name }}.zip
          path: src/stockfish.exe
