name: Windows build

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to build. If empty - build current.'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout fastchess repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'Disservin/fastchess'
          ref: ${{ inputs.commit }}

      - name: Checkout MINGW-packages repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'msys2/MINGW-packages'
          path: 'MINGW-packages'

      - name: Setup MSYS2 (UCRT64 environment)
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: >-
            git
            make
            mingw-w64-clang64-x86_64-clang

      - name: Extract version info
        id: version
        shell: msys2 {0}
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(git log -1 --format=%cs)
          ARTIFACT_NAME="fastchess-git-${COMMIT}-${DATE}-win64"
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
          
      - name: Configure and build 
        shell: msys2 {0}
        run: |
          export CFLAGS=" -O3 -static"
          export CXXFLAGS=$CFLAGS
          export CPPFLAGS=$CFLAGS
          export LDFLAGS="--static"
          make -j$(nproc) CXX=clang++

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.version.outputs.artifact_name }}.zip
          path: fastchess.exe
